-- HireConnect — PostgreSQL demo seed data
--
-- Password hashes below were generated by actually running
-- server/src/auth.ts's hashPassword() (real scrypt, not placeholders) and
-- verified with verifyPassword() before being pasted in here. Demo
-- passwords: job seekers/employers "Password123!", admin "AdminPass123!"
-- (override SEED_DEFAULT_PASSWORD/SEED_ADMIN_PASSWORD and regenerate before
-- using this anywhere beyond local/demo use — see server/src/seed.ts for
-- the equivalent SQLite seed script, which is the one actually exercised
-- by the test suite).
--
-- Run with: psql "$DATABASE_URL" -f database/postgres/seed.sql
-- (after migrations/0001_init.sql has been applied)

BEGIN;

INSERT INTO industries (name) VALUES
  ('Technology'), ('Finance & Banking'), ('Healthcare'), ('Manufacturing'), ('Agriculture'),
  ('Telecommunications'), ('Retail & E-commerce'), ('Logistics'), ('Media & Communications'), ('Education'),
  ('Construction'), ('Marketing'), ('Hospitality')
ON CONFLICT (name) DO NOTHING;

INSERT INTO job_categories (name) VALUES
  ('Software Engineering'), ('Product & Design'), ('Sales & Marketing'), ('Finance & Accounting'),
  ('Customer Support'), ('Human Resources'), ('Operations & Logistics'), ('Data & Analytics'), ('Media & Communications')
ON CONFLICT (name) DO NOTHING;

INSERT INTO skills (name) VALUES
  ('JavaScript'), ('TypeScript'), ('React'), ('Node.js'), ('Python'), ('Django'), ('SQL'), ('PostgreSQL'),
  ('AWS'), ('Docker'), ('Kubernetes'), ('Java'), ('Spring Boot'), ('Figma'), ('UI Design'), ('UX Research'),
  ('Digital Marketing'), ('SEO'), ('Content Writing'), ('Sales'), ('Negotiation'), ('Excel'),
  ('Financial Modeling'), ('Accounting'), ('QuickBooks'), ('Customer Service'), ('Zendesk'), ('Recruitment'),
  ('HR Policy'), ('Supply Chain'), ('Logistics Planning'), ('Data Analysis'), ('Power BI'), ('Machine Learning'),
  ('Mobile App Development'), ('Kotlin'), ('Swift'), ('PHP'), ('Laravel'), ('WordPress')
ON CONFLICT (name) DO NOTHING;

-- One demo employer + company, one demo candidate, one admin. This is a
-- deliberately small illustrative seed (unlike server/src/seed.ts's fuller
-- Kenyan dataset) since generating dozens of realistic rows in hand-written
-- SQL isn't a good use of this format — see the note at the bottom of this
-- file for how to seed the full dataset via a real Node script once `pg` is
-- installed.

INSERT INTO users (email, password_hash, role, email_verified, status) VALUES
  ('admin@hireconnect.co.ke', 'scrypt$af259ac4f033cdf86983af33cf41f620$01dead8d794d5f688c53d1daf71789ffaf2b8bc81eae285f7137a23fb9e6422fe9535cb8536891b776d05a295b620b02cfda9f29a30e4bb1cf3b66835cb9609f', 'admin', true, 'active'),
  ('employer1@twigadigitalsolutions.co.ke', 'scrypt$3f2742838401ec7ead0b7c914611670b$ce298cccb5ffc99d7c38d3b38f0b47b23195bb74943563c1fa0c9cf8b9eb297c755a3e14f640206be2f427ced2ff2bb3da13890bccb029cc0ed0e0f6bca5ca36', 'employer', true, 'active'),
  ('candidate1@example.com', 'scrypt$3f2742838401ec7ead0b7c914611670b$ce298cccb5ffc99d7c38d3b38f0b47b23195bb74943563c1fa0c9cf8b9eb297c755a3e14f640206be2f427ced2ff2bb3da13890bccb029cc0ed0e0f6bca5ca36', 'job_seeker', true, 'active')
ON CONFLICT (email) DO NOTHING;

INSERT INTO employer_profiles (user_id)
  SELECT id FROM users WHERE email = 'employer1@twigadigitalsolutions.co.ke'
ON CONFLICT (user_id) DO NOTHING;

INSERT INTO companies (owner_user_id, name, description, location, size, founded_year, culture, benefits, verified, status)
SELECT id, 'Twiga Digital Solutions', 'A fast-growing fintech and e-commerce technology company building for the East African market.',
       'Nairobi, Kenya', '51-200', 2015, 'Fast-paced, remote-friendly, engineering-led.', 'Health insurance, learning budget, hybrid work.', true, 'approved'
FROM users WHERE email = 'employer1@twigadigitalsolutions.co.ke'
ON CONFLICT DO NOTHING;

UPDATE employer_profiles SET company_id = (SELECT id FROM companies WHERE name = 'Twiga Digital Solutions')
WHERE user_id = (SELECT id FROM users WHERE email = 'employer1@twigadigitalsolutions.co.ke');

INSERT INTO candidate_profiles (user_id, full_name, headline, bio, location, years_experience, preferred_job_type, preferred_location, expected_salary_min, expected_salary_max, availability)
SELECT id, 'Jane Wanjiru', 'Backend Engineer', 'Backend engineer with 3 years of experience across Kenyan companies.',
       'Nairobi, Kenya', 3, 'full_time', 'Nairobi, Kenya', 120000, 180000, 'immediate'
FROM users WHERE email = 'candidate1@example.com'
ON CONFLICT (user_id) DO NOTHING;

INSERT INTO candidate_skills (candidate_id, skill_id, level)
SELECT cp.id, sk.id, 'advanced'
FROM candidate_profiles cp, skills sk
WHERE cp.user_id = (SELECT id FROM users WHERE email = 'candidate1@example.com')
  AND sk.name IN ('TypeScript', 'Node.js', 'PostgreSQL')
ON CONFLICT DO NOTHING;

INSERT INTO jobs (company_id, category_id, created_by, title, department, description, requirements, experience_level,
  employment_type, work_mode, location, salary_min, salary_max, openings, status)
SELECT c.id, jc.id, c.owner_user_id, 'Senior Backend Engineer', 'Software Engineering',
  'We are looking for a talented Senior Backend Engineer to join our team in Nairobi, Kenya.',
  'TypeScript, Node.js, PostgreSQL, AWS, Docker experience required.', 'senior', 'full_time', 'hybrid',
  'Nairobi, Kenya', 220000, 320000, 1, 'published'
FROM companies c JOIN job_categories jc ON jc.name = 'Software Engineering'
WHERE c.name = 'Twiga Digital Solutions'
ON CONFLICT DO NOTHING;

INSERT INTO job_skills (job_id, skill_id, required)
SELECT j.id, sk.id, true
FROM jobs j, skills sk
WHERE j.title = 'Senior Backend Engineer' AND sk.name IN ('TypeScript', 'Node.js', 'PostgreSQL', 'AWS', 'Docker')
ON CONFLICT DO NOTHING;

COMMIT;

-- To seed the FULL Kenyan demo dataset (10 companies, 22 jobs, 22
-- candidates, 44+ applications — matching server/src/seed.ts) against
-- Postgres, port that script to use `pg` instead of `node:sqlite`: the
-- SQL statements themselves barely change (mostly `?` -> `$1, $2, ...`
-- placeholders), since server/src/matching.ts's calculateMatch() and the
-- password hashing are already plain, dependency-free functions that work
-- identically against either database.
